name: flutter_dynamic_widget
description: A Dynamic Widget Runtime from Json to Flutter Widgets based on the
  json_widget spec.
version: 1.1.1
homepage: https://github.com/rodydavis/flutter_dynamic_widget
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0-10.0.pre.79 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  shortid: ^0.1.1
  url_launcher: ^5.4.7
  meta: ^1.1.8
  build_cli_annotations: ^1.2.0
  console: ^3.1.0
  mustache_template: ^1.0.0+1
  widget_gen:
    path: third_party/widget_gen

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_version: ^2.0.1
  build_runner: any
  build_cli: ^1.3.10
  flutter_ast:
    path: third_party/flutter_ast

flutter:
  uses-material-design: true
